version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 30
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: PuppeteerSharp
    versions:
    - 2.0.4
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
